<?php
namespace Models\Lists;

use Bitrix\Main\Entity\Query\Join;
use Bitrix\Main\Entity\ReferenceField;
use Models\AbstractIblockPropertyValuesTable;
use Models\Lists\DoctorsProcsPropertyValuesTable;


class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 17;

    public static function getMap(): array
    {
        $map = [
            'PROCEDURE' => new ReferenceField(//не \ReferenceField
                'PROCEDURE',
                DoctorsProcsPropertyValuesTable::class,
                ['=this.PROCEDURE_ID' => '=ref.IBLOCK_ELEMENT_ID']
            )
        ];

        // return array_merge(parent::getMap(),$map); // TODO: Change the autogenerated stub
        return parent::getMap()+$map; // TODO: Change the autogenerated stub

    }
}
